### ISSUE TITLE
Criar implementação em Memória para Repositorio das classes de Domínio

### ISSUE THREAD

**Issue by iceberg20** [iceberg20/TodoList#29]
@LuanGB está é a sua tarefa

**Comment by LuanGB** [comment]
Mano, essa atividade é referente às classes do de domínio da aplicação do professor (conta)... O nome das classes de domínio deve ser trocado...

**Comment by iceberg20** [comment]
Já corrigi o nome da tarefa.

**Comment by LuanGB** [comment]
Aewww... kkkk
